# Generated by Django 5.2 on 2025-05-02 02:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bodegas',
            fields=[
                ('id_bodega', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Bodega',
                'verbose_name_plural': 'Bodegas',
            },
        ),
        migrations.CreateModel(
            name='Maquinas',
            fields=[
                ('id_maquina', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('tipo_proceso', models.CharField(choices=[('Molido', 'Molido'), ('Lavado', 'Lavado'), ('Peletizado', 'Peletizado'), ('Inyeccion', 'Inyección')], max_length=20, verbose_name='Tipo de Proceso')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Máquina',
                'verbose_name_plural': 'Máquinas',
            },
        ),
        migrations.CreateModel(
            name='Materiales',
            fields=[
                ('id_material', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('tipo', models.CharField(choices=[('Molido', 'Molido'), ('Lavado', 'Lavado'), ('Peletizado', 'Peletizado'), ('Inyeccion', 'Inyección'), ('Original', 'Original'), ('Entero', 'Entero'), ('Aglutinada', 'Aglutinada'), ('Pigmento', 'Pigmento'), ('Aditivo', 'Aditivo')], max_length=20, verbose_name='Tipo')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiales',
            },
        ),
        migrations.CreateModel(
            name='Operarios',
            fields=[
                ('id_operario', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('nombre_completo', models.CharField(max_length=150, verbose_name='Nombre Completo')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Operario',
                'verbose_name_plural': 'Operarios',
            },
        ),
        migrations.CreateModel(
            name='Terceros',
            fields=[
                ('id_tercero', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('tipo', models.CharField(choices=[('Proveedor', 'Proveedor'), ('Cliente', 'Cliente')], max_length=10, verbose_name='Tipo')),
                ('identificacion', models.CharField(blank=True, max_length=50, null=True, verbose_name='Identificación (NIT)')),
                ('direccion', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('telefono', models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Tercero',
                'verbose_name_plural': 'Terceros',
            },
        ),
    ]
