# Generated by Django 5.2 on 2025-05-02 02:34

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lotes',
            fields=[
                ('id_lote', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_lote', models.CharField(max_length=50, unique=True, verbose_name='Número de Lote')),
                ('cantidad_inicial', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Cantidad Inicial')),
                ('cantidad_actual', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Cantidad Actual')),
                ('unidad_medida', models.CharField(choices=[('kg', 'Kilogramos'), ('unidad', 'Unidades')], default='kg', max_length=10, verbose_name='Unidad de Medida')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha Creación')),
                ('clasificacion', models.CharField(blank=True, choices=[('A1', 'A1'), ('A2', 'A2')], max_length=10, null=True, verbose_name='Clasificación (Molido/Lavado)')),
                ('origen_tipo', models.CharField(blank=True, choices=[('Compra', 'Compra'), ('IngresoServicio', 'Ingreso por Servicio'), ('ProduccionMolido', 'Producción Molido'), ('ProduccionLavado', 'Producción Lavado'), ('ProduccionPeletizado', 'Producción Peletizado'), ('ProduccionInyeccion', 'Producción Inyección'), ('AjustePositivo', 'Ajuste Positivo Inventario')], max_length=30, null=True, verbose_name='Tipo de Origen')),
                ('origen_referencia', models.CharField(blank=True, max_length=100, null=True, verbose_name='Referencia Origen (ID/Doc)')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo (con existencias)')),
                ('id_bodega_actual', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.bodegas', verbose_name='Bodega Actual')),
                ('id_material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.materiales', verbose_name='Material')),
            ],
            options={
                'verbose_name': 'Lote',
                'verbose_name_plural': 'Lotes',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='MovimientosInventario',
            fields=[
                ('id_movimiento', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha Movimiento')),
                ('tipo_movimiento', models.CharField(choices=[('Compra', 'Compra'), ('IngresoServicio', 'Ingreso por Servicio'), ('SalidaServicio', 'Salida por Servicio'), ('Traslado', 'Traslado'), ('Venta', 'Venta'), ('ConsumoProduccion', 'Consumo Producción'), ('AjustePositivo', 'Ajuste Positivo'), ('AjusteNegativo', 'Ajuste Negativo')], max_length=30, verbose_name='Tipo de Movimiento')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Cantidad Movida')),
                ('consecutivo_soporte', models.CharField(max_length=50, verbose_name='Consecutivo Soporte Interno')),
                ('factura_remision', models.CharField(blank=True, max_length=50, null=True, verbose_name='Factura/Remisión (Venta/Salida)')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('evidencia_info', models.CharField(blank=True, max_length=255, null=True, verbose_name='Información Evidencia (Ej: Ruta Foto)')),
                ('produccion_referencia', models.CharField(blank=True, max_length=100, null=True, verbose_name='Referencia Producción (ID)')),
                ('id_destino_bodega', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_entrada', to='gestion.bodegas', verbose_name='Bodega Destino')),
                ('id_destino_tercero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_recibe', to='gestion.terceros', verbose_name='Tercero Destino (Cliente)')),
                ('id_lote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.lotes', verbose_name='Lote Afectado')),
                ('id_origen_bodega', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_salida', to='gestion.bodegas', verbose_name='Bodega Origen')),
                ('id_origen_tercero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_entrega', to='gestion.terceros', verbose_name='Tercero Origen (Proveedor)')),
            ],
            options={
                'verbose_name': 'Movimiento de Inventario',
                'verbose_name_plural': 'Movimientos de Inventario',
                'ordering': ['-fecha'],
            },
        ),
    ]
