# Generated by Django 5.2 on 2025-05-02 02:52

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_lotes_movimientosinventario'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProduccionInyeccion',
            fields=[
                ('id_produccion', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha Producción')),
                ('turno', models.CharField(blank=True, max_length=50, null=True, verbose_name='Turno')),
                ('orden_trabajo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Orden de Trabajo')),
                ('cantidad_producida', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Cantidad Producida')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('numero_mezclas', models.PositiveIntegerField(default=1, verbose_name='Número de Mezclas')),
                ('id_bodega_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.bodegas', verbose_name='Bodega Destino Lote Producido')),
                ('id_lote_producido', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='produccion_inyeccion_origen', to='gestion.lotes', verbose_name='Lote Producido')),
                ('id_maquina', models.ForeignKey(limit_choices_to={'tipo_proceso': 'Inyeccion'}, on_delete=django.db.models.deletion.PROTECT, to='gestion.maquinas', verbose_name='Inyectora')),
                ('id_operario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.operarios', verbose_name='Operario')),
            ],
            options={
                'verbose_name': 'Producción Inyección',
                'verbose_name_plural': 'Producciones Inyección',
            },
        ),
        migrations.CreateModel(
            name='ProduccionLavado',
            fields=[
                ('id_produccion', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha Producción')),
                ('turno', models.CharField(blank=True, max_length=50, null=True, verbose_name='Turno')),
                ('orden_trabajo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Orden de Trabajo')),
                ('cantidad_producida', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Cantidad Producida')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('clasificacion_producida', models.CharField(blank=True, choices=[('A1', 'A1'), ('A2', 'A2')], max_length=10, null=True, verbose_name='Clasificación Producida')),
                ('id_bodega_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.bodegas', verbose_name='Bodega Destino Lote Producido')),
                ('id_lote_producido', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='produccion_lavado_origen', to='gestion.lotes', verbose_name='Lote Producido')),
                ('id_maquina', models.ForeignKey(limit_choices_to={'tipo_proceso': 'Lavado'}, on_delete=django.db.models.deletion.PROTECT, to='gestion.maquinas', verbose_name='Sistema Lavado')),
                ('id_operario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.operarios', verbose_name='Operario')),
            ],
            options={
                'verbose_name': 'Producción Lavado',
                'verbose_name_plural': 'Producciones Lavado',
            },
        ),
        migrations.CreateModel(
            name='ProduccionMolido',
            fields=[
                ('id_produccion', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha Producción')),
                ('turno', models.CharField(blank=True, max_length=50, null=True, verbose_name='Turno')),
                ('orden_trabajo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Orden de Trabajo')),
                ('cantidad_producida', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Cantidad Producida')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('clasificacion_producida', models.CharField(blank=True, choices=[('A1', 'A1'), ('A2', 'A2')], max_length=10, null=True, verbose_name='Clasificación Producida')),
                ('id_bodega_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.bodegas', verbose_name='Bodega Destino Lote Producido')),
                ('id_lote_producido', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='produccion_molido_origen', to='gestion.lotes', verbose_name='Lote Producido')),
                ('id_maquina', models.ForeignKey(limit_choices_to={'tipo_proceso': 'Molido'}, on_delete=django.db.models.deletion.PROTECT, to='gestion.maquinas', verbose_name='Molino')),
                ('id_operario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.operarios', verbose_name='Operario')),
            ],
            options={
                'verbose_name': 'Producción Molido',
                'verbose_name_plural': 'Producciones Molido',
            },
        ),
        migrations.CreateModel(
            name='ProduccionPeletizado',
            fields=[
                ('id_produccion', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha Producción')),
                ('turno', models.CharField(blank=True, max_length=50, null=True, verbose_name='Turno')),
                ('orden_trabajo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Orden de Trabajo')),
                ('cantidad_producida', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Cantidad Producida')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('numero_mezclas', models.PositiveIntegerField(default=1, verbose_name='Número de Mezclas')),
                ('id_bodega_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.bodegas', verbose_name='Bodega Destino Lote Producido')),
                ('id_lote_producido', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='produccion_peletizado_origen', to='gestion.lotes', verbose_name='Lote Producido')),
                ('id_maquina', models.ForeignKey(limit_choices_to={'tipo_proceso': 'Peletizado'}, on_delete=django.db.models.deletion.PROTECT, to='gestion.maquinas', verbose_name='Peletizadora')),
                ('id_operario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.operarios', verbose_name='Operario')),
            ],
            options={
                'verbose_name': 'Producción Peletizado',
                'verbose_name_plural': 'Producciones Peletizado',
            },
        ),
        migrations.CreateModel(
            name='ProduccionConsumo',
            fields=[
                ('id_consumo', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cantidad_consumida', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Cantidad Consumida')),
                ('id_bodega_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.bodegas', verbose_name='Bodega Origen Consumo')),
                ('id_lote_consumido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumos_en_produccion', to='gestion.lotes', verbose_name='Lote Consumido')),
                ('id_produccion_inyeccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consumos', to='gestion.produccioninyeccion')),
                ('id_produccion_lavado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consumos', to='gestion.produccionlavado')),
                ('id_produccion_molido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consumos', to='gestion.produccionmolido')),
                ('id_produccion_peletizado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consumos', to='gestion.produccionpeletizado')),
            ],
            options={
                'verbose_name': 'Consumo de Producción',
                'verbose_name_plural': 'Consumos de Producción',
            },
        ),
        migrations.CreateModel(
            name='ParosProduccion',
            fields=[
                ('id_paro', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha_hora_inicio', models.DateTimeField(verbose_name='Fecha/Hora Inicio Paro')),
                ('fecha_hora_fin', models.DateTimeField(verbose_name='Fecha/Hora Fin Paro')),
                ('motivo', models.TextField(verbose_name='Motivo del Paro')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('id_operario_reporta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.operarios', verbose_name='Operario que Reporta')),
                ('id_produccion_inyeccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paros', to='gestion.produccioninyeccion')),
                ('id_produccion_lavado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paros', to='gestion.produccionlavado')),
                ('id_produccion_molido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paros', to='gestion.produccionmolido')),
                ('id_produccion_peletizado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paros', to='gestion.produccionpeletizado')),
            ],
            options={
                'verbose_name': 'Paro de Producción',
                'verbose_name_plural': 'Paros de Producción',
                'ordering': ['-fecha_hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='ResiduosProduccion',
            fields=[
                ('id_residuo', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha Registro Residuo')),
                ('tipo_residuo', models.CharField(max_length=100, verbose_name='Tipo de Residuo')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad Residuo')),
                ('unidad_medida', models.CharField(choices=[('kg', 'Kilogramos'), ('unidad', 'Unidades')], default='kg', max_length=10, verbose_name='Unidad de Medida')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('id_produccion_inyeccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='residuos', to='gestion.produccioninyeccion')),
                ('id_produccion_lavado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='residuos', to='gestion.produccionlavado')),
                ('id_produccion_molido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='residuos', to='gestion.produccionmolido')),
                ('id_produccion_peletizado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='residuos', to='gestion.produccionpeletizado')),
            ],
            options={
                'verbose_name': 'Residuo de Producción',
                'verbose_name_plural': 'Residuos de Producción',
                'ordering': ['-fecha'],
            },
        ),
    ]
