# Generated by Django 5.2 on 2025-05-02 03:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_produccioninyeccion_produccionlavado_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lotes',
            name='origen_referencia',
        ),
        migrations.RemoveField(
            model_name='lotes',
            name='origen_tipo',
        ),
        migrations.RemoveField(
            model_name='movimientosinventario',
            name='evidencia_info',
        ),
        migrations.RemoveField(
            model_name='produccionlavado',
            name='clasificacion_producida',
        ),
        migrations.RemoveField(
            model_name='produccionmolido',
            name='clasificacion_producida',
        ),
        migrations.AddField(
            model_name='lotes',
            name='costo_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Costo Unitario'),
        ),
        migrations.AddField(
            model_name='lotes',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha Última Modificación'),
        ),
        migrations.AddField(
            model_name='lotes',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Vencimiento'),
        ),
        migrations.AddField(
            model_name='lotes',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lotes',
            name='proveedor_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes_proveidos', to='gestion.terceros', verbose_name='Proveedor Origen'),
        ),
        migrations.AddField(
            model_name='lotes',
            name='usuario_modificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Último Usuario Modificador'),
        ),
        migrations.AlterField(
            model_name='lotes',
            name='activo',
            field=models.BooleanField(default=True, editable=False, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='lotes',
            name='cantidad_actual',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Cantidad Actual'),
        ),
        migrations.AlterField(
            model_name='lotes',
            name='cantidad_inicial',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad Inicial'),
        ),
        migrations.AlterField(
            model_name='lotes',
            name='clasificacion',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=50, null=True, verbose_name='Clasificación Calidad'),
        ),
        migrations.AlterField(
            model_name='lotes',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación'),
        ),
        migrations.AlterField(
            model_name='lotes',
            name='numero_lote',
            field=models.CharField(max_length=100, unique=True, verbose_name='Número de Lote'),
        ),
        migrations.AlterField(
            model_name='lotes',
            name='unidad_medida',
            field=models.CharField(choices=[('kg', 'Kilogramos'), ('unidad', 'Unidades')], default='kg', max_length=10),
        ),
        migrations.AlterField(
            model_name='movimientosinventario',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad Movida'),
        ),
        migrations.AlterField(
            model_name='movimientosinventario',
            name='consecutivo_soporte',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Consecutivo Soporte (Factura/Remisión/OT)'),
        ),
        migrations.AlterField(
            model_name='movimientosinventario',
            name='factura_remision',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Factura/Remisión Asociada'),
        ),
        migrations.AlterField(
            model_name='movimientosinventario',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha Movimiento'),
        ),
        migrations.AlterField(
            model_name='movimientosinventario',
            name='id_destino_tercero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_recibe', to='gestion.terceros', verbose_name='Tercero Destino (Cliente/Proveedor)'),
        ),
        migrations.AlterField(
            model_name='movimientosinventario',
            name='id_origen_tercero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_entrega', to='gestion.terceros', verbose_name='Tercero Origen (Proveedor/Cliente)'),
        ),
        migrations.AlterField(
            model_name='movimientosinventario',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movimientosinventario',
            name='produccion_referencia',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID Producción Relacionada'),
        ),
        migrations.AlterField(
            model_name='movimientosinventario',
            name='tipo_movimiento',
            field=models.CharField(choices=[('Compra', 'Compra'), ('Venta', 'Venta'), ('Traslado', 'Traslado'), ('AjustePositivo', 'Ajuste Positivo'), ('AjusteNegativo', 'Ajuste Negativo'), ('ConsumoProduccion', 'Consumo Producción'), ('IngresoServicio', 'Ingreso por Servicio'), ('SalidaServicio', 'Salida a Servicio')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='lotes',
            index=models.Index(fields=['id_material', 'id_bodega_actual'], name='idx_lote_material_bodega'),
        ),
        migrations.AddIndex(
            model_name='lotes',
            index=models.Index(fields=['numero_lote'], name='idx_lote_numero'),
        ),
        migrations.AddConstraint(
            model_name='lotes',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad_actual__gte', 0)), name='check_cantidad_actual_no_negativa'),
        ),
    ]
