# Generated by Django 5.2 on 2025-05-08 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_remove_lotes_origen_referencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquinas',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='lotes',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha Modificación'),
        ),
        migrations.AlterField(
            model_name='parosproduccion',
            name='id_produccion_inyeccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paros_inyeccion', to='gestion.produccioninyeccion'),
        ),
        migrations.AlterField(
            model_name='parosproduccion',
            name='id_produccion_lavado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paros_lavado', to='gestion.produccionlavado'),
        ),
        migrations.AlterField(
            model_name='parosproduccion',
            name='id_produccion_molido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paros_molido', to='gestion.produccionmolido'),
        ),
        migrations.AlterField(
            model_name='parosproduccion',
            name='id_produccion_peletizado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paros_peletizado', to='gestion.produccionpeletizado'),
        ),
        migrations.AlterField(
            model_name='produccionconsumo',
            name='id_produccion_inyeccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consumos_inyeccion', to='gestion.produccioninyeccion'),
        ),
        migrations.AlterField(
            model_name='produccionconsumo',
            name='id_produccion_lavado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consumos_lavado', to='gestion.produccionlavado'),
        ),
        migrations.AlterField(
            model_name='produccionconsumo',
            name='id_produccion_molido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consumos_molido', to='gestion.produccionmolido'),
        ),
        migrations.AlterField(
            model_name='produccionconsumo',
            name='id_produccion_peletizado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consumos_peletizado', to='gestion.produccionpeletizado'),
        ),
        migrations.AlterField(
            model_name='residuosproduccion',
            name='id_produccion_inyeccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='residuos_inyeccion', to='gestion.produccioninyeccion'),
        ),
        migrations.AlterField(
            model_name='residuosproduccion',
            name='id_produccion_lavado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='residuos_lavado', to='gestion.produccionlavado'),
        ),
        migrations.AlterField(
            model_name='residuosproduccion',
            name='id_produccion_molido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='residuos_molido', to='gestion.produccionmolido'),
        ),
        migrations.AlterField(
            model_name='residuosproduccion',
            name='id_produccion_peletizado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='residuos_peletizado', to='gestion.produccionpeletizado'),
        ),
    ]
