# Generated by Django 4.2.9 on 2025-05-22 02:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_produccionpeletizado_completado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotivoParo',
            fields=[
                ('id_motivo', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Motivo')),
            ],
            options={
                'verbose_name': 'Motivo de Paro',
                'verbose_name_plural': 'Motivos de Paros',
            },
        ),
        migrations.AlterField(
            model_name='parosproduccion',
            name='motivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.motivoparo', verbose_name='Motivo del Paro'),
        ),
    ]
