# Generated by Django 4.2.9 on 2025-05-22 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_motivoparo_alter_parosproduccion_motivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='terceros',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
    ]
