# Generated by Django 4.2.9 on 2025-05-22 20:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestion', '0008_terceros_activo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Despacho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_remision', models.CharField(max_length=50, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_despacho', models.DateTimeField(blank=True, null=True)),
                ('direccion_entrega', models.CharField(max_length=255)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('despachado', 'Despachado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('tercero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='despachos', to='gestion.terceros')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='despachos_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Despacho',
                'verbose_name_plural': 'Despachos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.AddField(
            model_name='produccioninyeccion',
            name='archivo_adjunto',
            field=models.FileField(blank=True, null=True, upload_to='produccion/archivos/', verbose_name='Archivo Adjunto'),
        ),
        migrations.AddField(
            model_name='produccionlavado',
            name='archivo_adjunto',
            field=models.FileField(blank=True, null=True, upload_to='produccion/archivos/', verbose_name='Archivo Adjunto'),
        ),
        migrations.AddField(
            model_name='produccionmolido',
            name='archivo_adjunto',
            field=models.FileField(blank=True, null=True, upload_to='produccion/archivos/', verbose_name='Archivo Adjunto'),
        ),
        migrations.AddField(
            model_name='produccionpeletizado',
            name='archivo_adjunto',
            field=models.FileField(blank=True, null=True, upload_to='produccion/archivos/', verbose_name='Archivo Adjunto'),
        ),
        migrations.CreateModel(
            name='DetalleDespacho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bodega_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.bodegas')),
                ('despacho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='gestion.despacho')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.lotes')),
            ],
        ),
    ]
