# Generated by Django 4.2.21 on 2025-05-31 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0010_remove_produccioninyeccion_cantidad_producida_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiales',
            name='tipo',
            field=models.CharField(choices=[('MP', 'Materia Prima'), ('PI', 'Producto Intermedio'), ('PT', 'Producto Terminado'), ('IN', 'Insumo')], max_length=20, verbose_name='Tipo'),
        ),
    ]
