# Generated by Django 4.2.9 on 2025-07-16 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0011_alter_materiales_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='despacho',
            name='orden_compra',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Orden de Compra'),
        ),
    ]
