# Generated by Django 4.2.9 on 2025-07-16 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0012_despacho_orden_compra'),
    ]

    operations = [
        migrations.AddField(
            model_name='despacho',
            name='archivo_adjunto',
            field=models.FileField(blank=True, null=True, upload_to='despachos/archivos/', verbose_name='Archivo Adjunto'),
        ),
    ]
