# Generated by Django 4.2.9 on 2025-07-16 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0013_despacho_archivo_adjunto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produccioninyeccion',
            name='turno',
            field=models.CharField(blank=True, choices=[('6am-2pm', '6am-2pm'), ('6am-12pm', '6am-12pm'), ('12pm-6pm', '12pm-6pm'), ('2pm-10pm', '2pm-10pm'), ('10pm-6am', '10pm-6am'), ('6am-6pm', '6am-6pm'), ('6pm-6am', '6pm-6am')], max_length=50, null=True, verbose_name='Turno'),
        ),
        migrations.AlterField(
            model_name='produccionlavado',
            name='turno',
            field=models.CharField(blank=True, choices=[('6am-2pm', '6am-2pm'), ('6am-12pm', '6am-12pm'), ('12pm-6pm', '12pm-6pm'), ('2pm-10pm', '2pm-10pm'), ('10pm-6am', '10pm-6am'), ('6am-6pm', '6am-6pm'), ('6pm-6am', '6pm-6am')], max_length=50, null=True, verbose_name='Turno'),
        ),
        migrations.AlterField(
            model_name='produccionmolido',
            name='turno',
            field=models.CharField(blank=True, choices=[('6am-2pm', '6am-2pm'), ('6am-12pm', '6am-12pm'), ('12pm-6pm', '12pm-6pm'), ('2pm-10pm', '2pm-10pm'), ('10pm-6am', '10pm-6am'), ('6am-6pm', '6am-6pm'), ('6pm-6am', '6pm-6am')], max_length=50, null=True, verbose_name='Turno'),
        ),
        migrations.AlterField(
            model_name='produccionpeletizado',
            name='turno',
            field=models.CharField(blank=True, choices=[('6am-2pm', '6am-2pm'), ('6am-12pm', '6am-12pm'), ('12pm-6pm', '12pm-6pm'), ('2pm-10pm', '2pm-10pm'), ('10pm-6am', '10pm-6am'), ('6am-6pm', '6am-6pm'), ('6pm-6am', '6pm-6am')], max_length=50, null=True, verbose_name='Turno'),
        ),
    ]
