# Generated by Django 4.2.9 on 2025-07-16 13:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0014_alter_produccioninyeccion_turno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquinas',
            name='tipo_proceso',
            field=models.CharField(choices=[('Molido', 'Molido'), ('Lavado', 'Lavado'), ('Peletizado', 'Peletizado'), ('Inyeccion', 'Inyección'), ('Homogeneizacion', 'Homogeneización')], max_length=20, verbose_name='Tipo de Proceso'),
        ),
        migrations.CreateModel(
            name='ProduccionHomogeneizacion',
            fields=[
                ('id_produccion', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha Producción')),
                ('turno', models.CharField(blank=True, choices=[('6am-2pm', '6am-2pm'), ('6am-12pm', '6am-12pm'), ('12pm-6pm', '12pm-6pm'), ('2pm-10pm', '2pm-10pm'), ('10pm-6am', '10pm-6am'), ('6am-6pm', '6am-6pm'), ('6pm-6am', '6pm-6am')], max_length=50, null=True, verbose_name='Turno')),
                ('orden_trabajo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Orden de Trabajo')),
                ('cantidad_entrada', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Cantidad de Entrada')),
                ('cantidad_salida', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Cantidad de Salida')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('archivo_adjunto', models.FileField(blank=True, null=True, upload_to='produccion/archivos/', verbose_name='Archivo Adjunto')),
                ('merma', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Merma (Pérdida)')),
                ('id_bodega_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.bodegas', verbose_name='Bodega Destino Lote Producido')),
                ('id_lote_producido', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='produccion_homogeneizacion_origen', to='gestion.lotes', verbose_name='Lote Producido')),
                ('id_maquina', models.ForeignKey(limit_choices_to={'tipo_proceso': 'Homogeneizacion'}, on_delete=django.db.models.deletion.PROTECT, to='gestion.maquinas', verbose_name='Sistema Homogeneización')),
                ('id_operario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.operarios', verbose_name='Operario')),
            ],
            options={
                'verbose_name': 'Producción Homogeneización',
                'verbose_name_plural': 'Producciones Homogeneización',
            },
        ),
        migrations.AddField(
            model_name='parosproduccion',
            name='id_produccion_homogeneizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paros_homogeneizacion', to='gestion.produccionhomogeneizacion'),
        ),
        migrations.AddField(
            model_name='produccionconsumo',
            name='id_produccion_homogeneizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consumos_homogeneizacion', to='gestion.produccionhomogeneizacion'),
        ),
        migrations.AddField(
            model_name='residuosproduccion',
            name='id_produccion_homogeneizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='residuos_homogeneizacion', to='gestion.produccionhomogeneizacion'),
        ),
    ]
