# Generated by Django 4.2.9 on 2025-07-16 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestion', '0015_alter_maquinas_tipo_proceso_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_cliente', models.CharField(choices=[('corporativo', 'Corporativo'), ('pyme', 'PYME'), ('distribuidor', 'Distribuidor'), ('gobierno', 'Gobierno'), ('exportacion', 'Exportación')], max_length=20, verbose_name='Tipo de Cliente')),
                ('estado', models.CharField(choices=[('prospecto', 'Prospecto'), ('activo', 'Activo'), ('inactivo', 'Inactivo'), ('perdido', 'Perdido')], default='prospecto', max_length=20, verbose_name='Estado')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('fecha_ultima_interaccion', models.DateTimeField(blank=True, null=True, verbose_name='Última Interacción')),
                ('limite_credito', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Límite de Crédito')),
                ('dias_credito', models.IntegerField(default=0, verbose_name='Días de Crédito')),
                ('descuento_maximo', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Descuento Máximo %')),
                ('sitio_web', models.URLField(blank=True, null=True, verbose_name='Sitio Web')),
                ('industria', models.CharField(blank=True, max_length=100, null=True, verbose_name='Industria')),
                ('numero_empleados', models.IntegerField(blank=True, null=True, verbose_name='Número de Empleados')),
                ('facturacion_anual', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Facturación Anual')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('tercero', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cliente_crm', to='gestion.terceros')),
                ('usuario_asignado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clientes_asignados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Asignado')),
            ],
            options={
                'verbose_name': 'Cliente CRM',
                'verbose_name_plural': 'Clientes CRM',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id_contacto', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('cargo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cargo')),
                ('tipo_contacto', models.CharField(choices=[('principal', 'Contacto Principal'), ('compras', 'Compras'), ('finanzas', 'Finanzas'), ('tecnico', 'Técnico'), ('logistica', 'Logística'), ('otro', 'Otro')], max_length=20, verbose_name='Tipo de Contacto')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('celular', models.CharField(blank=True, max_length=20, null=True, verbose_name='Celular')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos', to='gestion.cliente')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contactos_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contactos',
                'ordering': ['nombre', 'apellido'],
            },
        ),
        migrations.CreateModel(
            name='Oportunidad',
            fields=[
                ('id_oportunidad', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre de la Oportunidad')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('etapa', models.CharField(choices=[('prospecto', 'Prospecto'), ('calificacion', 'Calificación'), ('presentacion', 'Presentación'), ('propuesta', 'Propuesta'), ('negociacion', 'Negociación'), ('cierre', 'Cierre'), ('ganada', 'Ganada'), ('perdida', 'Perdida')], default='prospecto', max_length=20, verbose_name='Etapa')),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('critica', 'Crítica')], default='media', max_length=20, verbose_name='Prioridad')),
                ('valor_estimado', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor Estimado')),
                ('probabilidad', models.IntegerField(default=50, verbose_name='Probabilidad (%)')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_cierre_estimada', models.DateField(verbose_name='Fecha de Cierre Estimada')),
                ('fecha_cierre_real', models.DateField(blank=True, null=True, verbose_name='Fecha de Cierre Real')),
                ('proximo_paso', models.CharField(blank=True, max_length=200, null=True, verbose_name='Próximo Paso')),
                ('fecha_proximo_paso', models.DateField(blank=True, null=True, verbose_name='Fecha Próximo Paso')),
                ('motivo_perdida', models.TextField(blank=True, null=True, verbose_name='Motivo de Pérdida')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oportunidades', to='gestion.cliente')),
                ('contacto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='oportunidades', to='gestion.contacto')),
                ('usuario_asignado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='oportunidades_asignadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Oportunidad',
                'verbose_name_plural': 'Oportunidades',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='InteraccionCliente',
            fields=[
                ('id_interaccion', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('llamada', 'Llamada'), ('email', 'Email'), ('reunion', 'Reunión'), ('visita', 'Visita'), ('cotizacion', 'Cotización'), ('seguimiento', 'Seguimiento'), ('otro', 'Otro')], max_length=20, verbose_name='Tipo de Interacción')),
                ('asunto', models.CharField(max_length=200, verbose_name='Asunto')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('fecha_interaccion', models.DateTimeField(verbose_name='Fecha de Interacción')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('requiere_seguimiento', models.BooleanField(default=False, verbose_name='Requiere Seguimiento')),
                ('fecha_seguimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Seguimiento')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interacciones', to='gestion.cliente')),
                ('contacto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='interacciones', to='gestion.contacto')),
                ('oportunidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interacciones', to='gestion.oportunidad')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interacciones_registradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Interacción',
                'verbose_name_plural': 'Interacciones',
                'ordering': ['-fecha_interaccion'],
            },
        ),
    ]
