# Generated by Django 4.2.7 on 2025-07-16 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestion', '0016_cliente_contacto_oportunidad_interaccioncliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_pedido', models.CharField(max_length=50, unique=True, verbose_name='Número de Pedido')),
                ('fecha_pedido', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del Pedido')),
                ('fecha_requerida', models.DateField(verbose_name='Fecha Requerida')),
                ('fecha_entrega', models.DateField(blank=True, null=True, verbose_name='Fecha de Entrega Real')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('confirmado', 'Confirmado'), ('en_produccion', 'En Producción'), ('parcial', 'Entrega Parcial'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='borrador', max_length=20, verbose_name='Estado')),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('normal', 'Normal'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='normal', max_length=20, verbose_name='Prioridad')),
                ('orden_compra_cliente', models.CharField(blank=True, max_length=100, null=True, verbose_name='Orden de Compra Cliente')),
                ('condiciones_pago', models.CharField(max_length=100, verbose_name='Condiciones de Pago')),
                ('direccion_entrega', models.TextField(verbose_name='Dirección de Entrega')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Subtotal')),
                ('descuento_porcentaje', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Descuento %')),
                ('descuento_valor', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Valor Descuento')),
                ('iva', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='IVA')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('notas_internas', models.TextField(blank=True, null=True, verbose_name='Notas Internas')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='gestion.cliente')),
                ('contacto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='gestion.contacto')),
                ('oportunidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='gestion.oportunidad')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-fecha_pedido'],
            },
        ),
        migrations.CreateModel(
            name='OrdenProduccion',
            fields=[
                ('id_orden', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_orden', models.CharField(max_length=50, unique=True, verbose_name='Número de Orden')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_programada_inicio', models.DateTimeField(verbose_name='Fecha Programada de Inicio')),
                ('fecha_programada_fin', models.DateTimeField(verbose_name='Fecha Programada de Fin')),
                ('fecha_real_inicio', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Real de Inicio')),
                ('fecha_real_fin', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Real de Fin')),
                ('estado', models.CharField(choices=[('programada', 'Programada'), ('en_proceso', 'En Proceso'), ('pausada', 'Pausada'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='programada', max_length=20, verbose_name='Estado')),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('normal', 'Normal'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='normal', max_length=20, verbose_name='Prioridad')),
                ('porcentaje_avance', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='% Avance')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('instrucciones_especiales', models.TextField(blank=True, null=True, verbose_name='Instrucciones Especiales')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_produccion', to='gestion.pedido')),
                ('supervisor_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_supervisadas', to=settings.AUTH_USER_MODEL)),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Orden de Producción',
                'verbose_name_plural': 'Órdenes de Producción',
                'ordering': ['-prioridad', 'fecha_programada_inicio'],
            },
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id_detalle', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descripcion_adicional', models.CharField(blank=True, max_length=500, null=True, verbose_name='Descripción Adicional')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Cantidad')),
                ('unidad_medida', models.CharField(max_length=20, verbose_name='Unidad de Medida')),
                ('cantidad_entregada', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Cantidad Entregada')),
                ('especificaciones', models.JSONField(blank=True, null=True, verbose_name='Especificaciones Técnicas')),
                ('requiere_proceso_especial', models.BooleanField(default=False, verbose_name='Requiere Proceso Especial')),
                ('proceso_especial', models.TextField(blank=True, null=True, verbose_name='Descripción Proceso Especial')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Precio Unitario')),
                ('descuento_porcentaje', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Descuento %')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Subtotal')),
                ('fecha_requerida', models.DateField(blank=True, null=True, verbose_name='Fecha Requerida Específica')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.materiales', verbose_name='Material')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='gestion.pedido')),
            ],
            options={
                'verbose_name': 'Detalle de Pedido',
                'verbose_name_plural': 'Detalles de Pedido',
                'ordering': ['pedido', 'material'],
            },
        ),
        migrations.CreateModel(
            name='DetalleOrdenProduccion',
            fields=[
                ('id_detalle', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cantidad_producir', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Cantidad a Producir')),
                ('cantidad_producida', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Cantidad Producida')),
                ('unidad_medida', models.CharField(max_length=20, verbose_name='Unidad de Medida')),
                ('secuencia_procesos', models.JSONField(verbose_name='Secuencia de Procesos')),
                ('tiempo_estimado_total', models.IntegerField(verbose_name='Tiempo Estimado Total (minutos)')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Fin')),
                ('detalle_pedido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_detalle', to='gestion.detallepedido')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.materiales', verbose_name='Material a Producir')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='gestion.ordenproduccion')),
            ],
            options={
                'verbose_name': 'Detalle de Orden de Producción',
                'verbose_name_plural': 'Detalles de Orden de Producción',
                'ordering': ['orden', 'material'],
            },
        ),
        migrations.CreateModel(
            name='PlanificacionProcesos',
            fields=[
                ('id_planificacion', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_proceso', models.CharField(choices=[('molido', 'Molido'), ('lavado', 'Lavado'), ('peletizado', 'Peletizado'), ('inyeccion', 'Inyección'), ('homogeneizacion', 'Homogeneización')], max_length=20, verbose_name='Tipo de Proceso')),
                ('secuencia', models.IntegerField(verbose_name='Orden en la Secuencia')),
                ('fecha_programada', models.DateTimeField(verbose_name='Fecha Programada')),
                ('duracion_estimada', models.IntegerField(verbose_name='Duración Estimada (minutos)')),
                ('orden_trabajo', models.CharField(max_length=100, unique=True, verbose_name='Orden de Trabajo')),
                ('estado', models.CharField(choices=[('programado', 'Programado'), ('en_proceso', 'En Proceso'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='programado', max_length=20, verbose_name='Estado')),
                ('fecha_inicio_real', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Inicio Real')),
                ('fecha_fin_real', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Fin Real')),
                ('cantidad_procesada', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Cantidad Procesada')),
                ('produccion_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID Producción Asociada')),
                ('detalle_orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planificaciones', to='gestion.detalleordenproduccion')),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion.maquinas', verbose_name='Máquina Asignada')),
                ('operario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Operario Asignado')),
            ],
            options={
                'verbose_name': 'Planificación de Proceso',
                'verbose_name_plural': 'Planificaciones de Procesos',
                'ordering': ['detalle_orden', 'secuencia'],
                'indexes': [models.Index(fields=['orden_trabajo'], name='gestion_pla_orden_t_f89d57_idx'), models.Index(fields=['tipo_proceso', 'estado'], name='gestion_pla_tipo_pr_594034_idx'), models.Index(fields=['fecha_programada'], name='gestion_pla_fecha_p_cf9004_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['numero_pedido'], name='gestion_ped_numero__dc5c05_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['cliente', 'estado'], name='gestion_ped_cliente_282e12_idx'),
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['fecha_requerida'], name='gestion_ped_fecha_r_206ba0_idx'),
        ),
        migrations.AddIndex(
            model_name='ordenproduccion',
            index=models.Index(fields=['numero_orden'], name='gestion_ord_numero__a805d6_idx'),
        ),
        migrations.AddIndex(
            model_name='ordenproduccion',
            index=models.Index(fields=['estado', 'prioridad'], name='gestion_ord_estado_e92bbc_idx'),
        ),
        migrations.AddIndex(
            model_name='ordenproduccion',
            index=models.Index(fields=['fecha_programada_inicio'], name='gestion_ord_fecha_p_f3577a_idx'),
        ),
    ]
