# Generated by Django 4.2.9 on 2025-07-16 16:08

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestion', '0017_pedido_ordenproduccion_detallepedido_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantillaTarea',
            fields=[
                ('id_plantilla', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('modulo', models.CharField(choices=[('crm', 'CRM'), ('pedidos', 'Pedidos'), ('ordenes', 'Órdenes de Producción'), ('produccion', 'Producción'), ('inventario', 'Inventario'), ('general', 'General')], max_length=20, verbose_name='Módulo')),
                ('titulo_template', models.CharField(max_length=200, verbose_name='Título de la Tarea')),
                ('descripcion_template', models.TextField(verbose_name='Descripción de la Tarea')),
                ('tipo', models.CharField(choices=[('seguimiento', 'Seguimiento'), ('accion', 'Acción Requerida'), ('revision', 'Revisión'), ('aprobacion', 'Aprobación'), ('recordatorio', 'Recordatorio'), ('incidencia', 'Incidencia')], max_length=20, verbose_name='Tipo')),
                ('prioridad_default', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='media', max_length=10, verbose_name='Prioridad por Defecto')),
                ('dias_para_vencer', models.IntegerField(default=7, verbose_name='Días para Vencer')),
                ('subtareas_template', models.JSONField(default=list, help_text='Lista de subtareas a crear', verbose_name='Subtareas')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('trigger', models.CharField(blank=True, choices=[('nueva_oportunidad', 'Nueva Oportunidad CRM'), ('pedido_confirmado', 'Pedido Confirmado'), ('orden_creada', 'Orden de Producción Creada'), ('produccion_iniciada', 'Producción Iniciada'), ('cliente_nuevo', 'Cliente Nuevo')], max_length=50, verbose_name='Trigger Automático')),
            ],
            options={
                'verbose_name': 'Plantilla de Tarea',
                'verbose_name_plural': 'Plantillas de Tareas',
                'db_table': 'plantillas_tarea',
                'ordering': ['modulo', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id_tarea', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('tipo', models.CharField(choices=[('seguimiento', 'Seguimiento'), ('accion', 'Acción Requerida'), ('revision', 'Revisión'), ('aprobacion', 'Aprobación'), ('recordatorio', 'Recordatorio'), ('incidencia', 'Incidencia')], max_length=20, verbose_name='Tipo')),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='media', max_length=10, verbose_name='Prioridad')),
                ('modulo_origen', models.CharField(choices=[('crm', 'CRM'), ('pedidos', 'Pedidos'), ('ordenes', 'Órdenes de Producción'), ('produccion', 'Producción'), ('inventario', 'Inventario'), ('general', 'General')], max_length=20, verbose_name='Módulo Origen')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_vencimiento', models.DateTimeField(verbose_name='Fecha de Vencimiento')),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Inicio')),
                ('fecha_completado', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Completado')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_progreso', 'En Progreso'), ('pausada', 'Pausada'), ('completada', 'Completada'), ('cancelada', 'Cancelada'), ('vencida', 'Vencida')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('porcentaje_avance', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Porcentaje de Avance')),
                ('etiquetas', models.JSONField(blank=True, default=list, verbose_name='Etiquetas')),
                ('categoria', models.CharField(blank=True, max_length=100, verbose_name='Categoría')),
                ('enviar_recordatorio', models.BooleanField(default=True, verbose_name='Enviar Recordatorio')),
                ('dias_antes_recordatorio', models.IntegerField(default=1, verbose_name='Días Antes del Recordatorio')),
                ('recordatorio_enviado', models.BooleanField(default=False, verbose_name='Recordatorio Enviado')),
                ('asignado_a', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tareas_asignadas', to=settings.AUTH_USER_MODEL, verbose_name='Asignado a')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas', to='gestion.cliente', verbose_name='Cliente')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tareas_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('equipo', models.ManyToManyField(blank=True, related_name='tareas_equipo', to=settings.AUTH_USER_MODEL, verbose_name='Equipo')),
                ('oportunidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas', to='gestion.oportunidad', verbose_name='Oportunidad')),
                ('orden_produccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas', to='gestion.ordenproduccion', verbose_name='Orden de Producción')),
                ('pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas', to='gestion.pedido', verbose_name='Pedido')),
            ],
            options={
                'verbose_name': 'Tarea',
                'verbose_name_plural': 'Tareas',
                'db_table': 'tareas',
                'ordering': ['-prioridad', 'fecha_vencimiento'],
            },
        ),
        migrations.CreateModel(
            name='Subtarea',
            fields=[
                ('id_subtarea', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('completada', models.BooleanField(default=False, verbose_name='Completada')),
                ('orden', models.IntegerField(default=0, verbose_name='Orden')),
                ('fecha_completado', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Completado')),
                ('completado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Completado por')),
                ('tarea_padre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtareas', to='gestion.tarea', verbose_name='Tarea Padre')),
            ],
            options={
                'verbose_name': 'Subtarea',
                'verbose_name_plural': 'Subtareas',
                'db_table': 'subtareas',
                'ordering': ['orden', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='ComentarioTarea',
            fields=[
                ('id_comentario', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comentario', models.TextField(verbose_name='Comentario')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('archivos_adjuntos', models.JSONField(blank=True, default=list, verbose_name='Archivos Adjuntos')),
                ('es_interno', models.BooleanField(default=False, help_text='Marcar para notas internas no visibles al cliente', verbose_name='Es Interno')),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='gestion.tarea', verbose_name='Tarea')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Comentario de Tarea',
                'verbose_name_plural': 'Comentarios de Tareas',
                'db_table': 'comentarios_tarea',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddIndex(
            model_name='tarea',
            index=models.Index(fields=['estado', 'asignado_a'], name='tareas_estado_193590_idx'),
        ),
        migrations.AddIndex(
            model_name='tarea',
            index=models.Index(fields=['modulo_origen', 'estado'], name='tareas_modulo__9dd6db_idx'),
        ),
        migrations.AddIndex(
            model_name='tarea',
            index=models.Index(fields=['fecha_vencimiento'], name='tareas_fecha_v_9a317f_idx'),
        ),
    ]
