# Generated by Django 4.2.7 on 2025-07-16 17:19

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestion', '0018_plantillatarea_tarea_subtarea_comentariotarea_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PQRS',
            fields=[
                ('id_pqrs', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_pqrs', models.CharField(max_length=20, unique=True, verbose_name='Número PQRS')),
                ('tipo', models.CharField(choices=[('peticion', 'Petición'), ('queja', 'Queja'), ('reclamo', 'Reclamo'), ('sugerencia', 'Sugerencia'), ('felicitacion', 'Felicitación')], max_length=20, verbose_name='Tipo')),
                ('nombre_contacto', models.CharField(max_length=200, verbose_name='Nombre del Contacto')),
                ('email_contacto', models.EmailField(max_length=254, verbose_name='Email del Contacto')),
                ('telefono_contacto', models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono')),
                ('asunto', models.CharField(max_length=200, verbose_name='Asunto')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('canal_recepcion', models.CharField(choices=[('web', 'Sitio Web'), ('email', 'Email'), ('telefono', 'Teléfono'), ('presencial', 'Presencial'), ('whatsapp', 'WhatsApp'), ('chat', 'Chat'), ('otro', 'Otro')], max_length=20, verbose_name='Canal de Recepción')),
                ('estado', models.CharField(choices=[('recibida', 'Recibida'), ('en_proceso', 'En Proceso'), ('escalada', 'Escalada'), ('solucionada', 'Solucionada'), ('cerrada', 'Cerrada'), ('cancelada', 'Cancelada')], default='recibida', max_length=20, verbose_name='Estado')),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('critica', 'Crítica')], default='media', max_length=20, verbose_name='Prioridad')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_asignacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Asignación')),
                ('fecha_primera_respuesta', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Primera Respuesta')),
                ('fecha_solucion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Solución')),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Cierre')),
                ('fecha_vencimiento', models.DateTimeField(verbose_name='Fecha de Vencimiento')),
                ('solucion', models.TextField(blank=True, null=True, verbose_name='Solución')),
                ('satisfaccion_cliente', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Satisfacción del Cliente (1-5)')),
                ('archivos_adjuntos', models.JSONField(blank=True, default=list, verbose_name='Archivos Adjuntos')),
                ('enviar_recordatorio', models.BooleanField(default=True, verbose_name='Enviar Recordatorio')),
                ('recordatorio_enviado', models.BooleanField(default=False, verbose_name='Recordatorio Enviado')),
                ('tiempo_respuesta', models.DurationField(blank=True, null=True, verbose_name='Tiempo de Respuesta')),
                ('tiempo_solucion', models.DurationField(blank=True, null=True, verbose_name='Tiempo de Solución')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pqrs', to='gestion.cliente', verbose_name='Cliente')),
                ('oportunidad_relacionada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pqrs', to='gestion.oportunidad', verbose_name='Oportunidad Relacionada')),
                ('pedido_relacionado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pqrs', to='gestion.pedido', verbose_name='Pedido Relacionado')),
                ('usuario_asignado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pqrs_asignadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Asignado')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pqrs_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que Registró')),
            ],
            options={
                'verbose_name': 'PQRS',
                'verbose_name_plural': 'PQRS',
                'db_table': 'pqrs',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='SeguimientoPQRS',
            fields=[
                ('id_seguimiento', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_seguimiento', models.CharField(choices=[('respuesta', 'Respuesta al Cliente'), ('nota_interna', 'Nota Interna'), ('escalamiento', 'Escalamiento'), ('solucion', 'Solución'), ('cambio_estado', 'Cambio de Estado')], max_length=20, verbose_name='Tipo de Seguimiento')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('archivos_adjuntos', models.JSONField(blank=True, default=list, verbose_name='Archivos Adjuntos')),
                ('visible_cliente', models.BooleanField(default=True, verbose_name='Visible para Cliente')),
                ('notificar_cliente', models.BooleanField(default=True, verbose_name='Notificar al Cliente')),
                ('estado_anterior', models.CharField(blank=True, max_length=20, null=True, verbose_name='Estado Anterior')),
                ('estado_nuevo', models.CharField(blank=True, max_length=20, null=True, verbose_name='Estado Nuevo')),
                ('pqrs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='gestion.pqrs', verbose_name='PQRS')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Seguimiento PQRS',
                'verbose_name_plural': 'Seguimientos PQRS',
                'db_table': 'seguimiento_pqrs',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddIndex(
            model_name='pqrs',
            index=models.Index(fields=['estado', 'prioridad'], name='pqrs_estado_5608b8_idx'),
        ),
        migrations.AddIndex(
            model_name='pqrs',
            index=models.Index(fields=['tipo', 'fecha_creacion'], name='pqrs_tipo_3ebedd_idx'),
        ),
        migrations.AddIndex(
            model_name='pqrs',
            index=models.Index(fields=['usuario_asignado', 'estado'], name='pqrs_usuario_1789bc_idx'),
        ),
        migrations.AddIndex(
            model_name='pqrs',
            index=models.Index(fields=['fecha_vencimiento'], name='pqrs_fecha_v_3adedf_idx'),
        ),
    ]
